//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YungChingProgram.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColumnCRUD
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string Tel { get; set; }
        public string Type { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> Updatetime { get; set; }
        public Nullable<System.DateTime> Crdatetime { get; set; }
        public string Cruser { get; set; }
        public string Upuser { get; set; }
    }
}
